import { useState, useEffect } from "react";
import { motion } from "motion/react";
import { 
  LineChart, 
  Line, 
  XAxis, 
  YAxis, 
  CartesianGrid, 
  Tooltip, 
  ResponsiveContainer,
  AreaChart,
  Area,
  BarChart,
  Bar,
  Legend
} from "recharts";
import { 
  TrendingUp, 
  Download, 
  Calendar, 
  Filter,
  BarChart3,
  Activity,
  FileDown
} from "lucide-react";
import { SymptomLog } from "../types";
import { cn } from "../lib/utils";
import jsPDF from "jspdf";

export default function Analytics() {
  const [logs, setLogs] = useState<SymptomLog[]>([]);
  const [timeRange, setTimeRange] = useState("7d");

  useEffect(() => {
    const savedLogs = localStorage.getItem("ra_logs");
    if (savedLogs) {
      const parsedLogs = JSON.parse(savedLogs);
      // Sort by date and format for charts
      const sorted = parsedLogs.sort((a: any, b: any) => new Date(a.date).getTime() - new Date(b.date).getTime());
      setLogs(sorted);
    }
  }, []);

  const chartData = logs.map(log => ({
    date: new Date(log.date).toLocaleDateString('default', { day: 'numeric', month: 'short' }),
    pain: log.painLevel,
    fatigue: log.fatigueLevel,
    stiffness: log.stiffnessMinutes / 20, // Scaled for comparison
    sleep: log.sleepHours,
    exercise: log.exerciseMinutes
  }));

  const exportPDF = () => {
    const doc = new jsPDF();
    doc.setFontSize(22);
    doc.text("RA Care AI Health Report", 20, 20);
    doc.setFontSize(12);
    doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 20, 30);
    
    doc.text("Recent Activity Summary:", 20, 50);
    logs.slice(-5).forEach((log, i) => {
      doc.text(`${log.date}: Pain ${log.painLevel}/10, Stiffness ${log.stiffnessMinutes}m`, 25, 60 + (i * 10));
    });

    doc.text("Disclaimer: This report is generated by AI for educational purposes.", 20, 280);
    doc.save("RA-Health-Report.pdf");
  };

  return (
    <div className="max-w-7xl mx-auto space-y-8 pb-12">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-extrabold tracking-tight text-slate-900">Health Analytics</h1>
          <p className="text-slate-500">Visualize your symptom trends and lifestyle correlations.</p>
        </div>
        <div className="flex items-center gap-3">
          <div className="flex bg-white border border-slate-200 rounded-xl p-1 shadow-sm">
            {["7d", "30d", "All"].map((r) => (
              <button
                key={r}
                onClick={() => setTimeRange(r)}
                className={cn(
                  "px-4 py-1.5 rounded-lg text-sm font-bold transition-all",
                  timeRange === r ? "bg-slate-900 text-white shadow-sm" : "text-slate-500 hover:text-slate-900"
                )}
              >
                {r}
              </button>
            ))}
          </div>
          <button 
            onClick={exportPDF}
            className="flex items-center gap-2 bg-blue-600 text-white px-5 py-2.5 rounded-xl font-bold hover:bg-blue-700 transition-all shadow-lg shadow-blue-100"
          >
            <FileDown className="w-4 h-4" />
            Export PDF
          </button>
        </div>
      </div>

      {logs.length < 2 ? (
        <div className="bg-white p-20 rounded-3xl border border-slate-200 text-center">
          <div className="w-20 h-20 bg-slate-50 rounded-full flex items-center justify-center mx-auto mb-6">
            <TrendingUp className="text-slate-300 w-10 h-10" />
          </div>
          <h2 className="text-xl font-bold text-slate-900 mb-2">Insufficient Data</h2>
          <p className="text-slate-500 max-w-sm mx-auto">Log your symptoms for at least 2 days to generate meaningful health trend visualizations.</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* Pain & Fatigue Trends */}
          <motion.div 
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="bg-white p-8 rounded-3xl border border-slate-200 shadow-sm"
          >
            <div className="flex items-center justify-between mb-8">
              <h3 className="text-lg font-bold text-slate-900 flex items-center gap-2">
                <Activity className="w-5 h-5 text-rose-500" />
                Pain & Fatigue Trends
              </h3>
              <div className="flex gap-4">
                <div className="flex items-center gap-2">
                  <div className="w-3 h-3 rounded-full bg-rose-500" />
                  <span className="text-xs font-bold text-slate-500 uppercase">Pain</span>
                </div>
                <div className="flex items-center gap-2">
                  <div className="w-3 h-3 rounded-full bg-amber-500" />
                  <span className="text-xs font-bold text-slate-500 uppercase">Fatigue</span>
                </div>
              </div>
            </div>
            <div className="h-[300px] w-full">
              <ResponsiveContainer width="100%" height="100%">
                <AreaChart data={chartData}>
                  <defs>
                    <linearGradient id="colorPain" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="#f43f5e" stopOpacity={0.1}/>
                      <stop offset="95%" stopColor="#f43f5e" stopOpacity={0}/>
                    </linearGradient>
                  </defs>
                  <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9" />
                  <XAxis 
                    dataKey="date" 
                    axisLine={false} 
                    tickLine={false} 
                    tick={{ fill: '#94a3b8', fontSize: 12, fontWeight: 600 }}
                  />
                  <YAxis 
                    axisLine={false} 
                    tickLine={false} 
                    tick={{ fill: '#94a3b8', fontSize: 12, fontWeight: 600 }}
                    domain={[0, 10]}
                  />
                  <Tooltip 
                    contentStyle={{ borderRadius: '16px', border: 'none', boxShadow: '0 10px 15px -3px rgb(0 0 0 / 0.1)' }}
                  />
                  <Area type="monotone" dataKey="pain" stroke="#f43f5e" strokeWidth={3} fillOpacity={1} fill="url(#colorPain)" />
                  <Line type="monotone" dataKey="fatigue" stroke="#f59e0b" strokeWidth={3} dot={{ r: 4, fill: '#f59e0b' }} />
                </AreaChart>
              </ResponsiveContainer>
            </div>
          </motion.div>

          {/* Activity Correlation */}
          <motion.div 
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ delay: 0.1 }}
            className="bg-white p-8 rounded-3xl border border-slate-200 shadow-sm"
          >
            <div className="flex items-center justify-between mb-8">
              <h3 className="text-lg font-bold text-slate-900 flex items-center gap-2">
                <BarChart3 className="w-5 h-5 text-blue-500" />
                Exercise & Sleep Impact
              </h3>
            </div>
            <div className="h-[300px] w-full">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={chartData}>
                  <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9" />
                  <XAxis dataKey="date" axisLine={false} tickLine={false} tick={{ fill: '#94a3b8', fontSize: 12 }} />
                  <YAxis axisLine={false} tickLine={false} tick={{ fill: '#94a3b8', fontSize: 12 }} />
                  <Tooltip cursor={{ fill: '#f8fafc' }} contentStyle={{ borderRadius: '16px', border: 'none' }} />
                  <Legend verticalAlign="top" align="right" iconType="circle" />
                  <Bar dataKey="sleep" name="Sleep (Hrs)" fill="#6366f1" radius={[4, 4, 0, 0]} />
                  <Bar dataKey="exercise" name="Exercise (Mins)" fill="#22c55e" radius={[4, 4, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </motion.div>

          {/* Morning Stiffness Intensity */}
          <motion.div 
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ delay: 0.2 }}
            className="lg:col-span-2 bg-white p-8 rounded-3xl border border-slate-200 shadow-sm"
          >
            <div className="flex items-center justify-between mb-8">
              <h3 className="text-lg font-bold text-slate-900">Joint Stiffness Progression</h3>
              <p className="text-sm text-slate-500 font-medium italic">Measured in minutes after waking</p>
            </div>
            <div className="h-[300px] w-full">
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={logs}>
                  <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9" />
                  <XAxis dataKey="date" axisLine={false} tickLine={false} tick={{ fill: '#94a3b8', fontSize: 12 }} 
                    tickFormatter={(val) => new Date(val).getDate().toString()}
                  />
                  <YAxis axisLine={false} tickLine={false} tick={{ fill: '#94a3b8', fontSize: 12 }} />
                  <Tooltip contentStyle={{ borderRadius: '16px', border: 'none' }} />
                  <Line 
                    type="stepAfter" 
                    dataKey="stiffnessMinutes" 
                    stroke="#8b5cf6" 
                    strokeWidth={4} 
                    dot={{ r: 6, fill: '#8b5cf6', strokeWidth: 2, stroke: '#fff' }} 
                  />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </motion.div>
        </div>
      )}
    </div>
  );
}
